### ISSUE TITLE
Symbol's function definition is void: equalp

### ISSUE THREAD

**Issue by jojojames** [nicklanasa/xcode-mode#13]
Running tests results in above error message.

james at jamesretina in ~/.emacs.d/fork/xcode-mode on master ./run-tests.sh
Symbol's function definition is void: equalp

Cask setup log
james at jamesretina in ~/.emacs.d/fork/xcode-mode on master cask
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: melpa.org:443
Opening TLS connection to `melpa.org'...
Opening TLS connection with`gnutls-cli --insecure -p 443 melpa.org'...
Opening TLS connection with `gnutls-cli --insecure -p 443 melpa.org'...done
Opening TLS connection to`melpa.org'...done
Contacting host: melpa.org:443
Opening TLS connection to `elpa.gnu.org'...
Opening TLS connection with`gnutls-cli --insecure -p 443 elpa.gnu.org'...
Opening TLS connection with `gnutls-cli --insecure -p 443 elpa.gnu.org'...done
Opening TLS connection to`elpa.gnu.org'...done
Contacting host: elpa.gnu.org:443
Contacting host: melpa.org:443
Making version-control local to s-autoloads.el while let-bound!
Generating autoloads for s.el...
Generating autoloads for s.el...done
Saving file /Users/james/.emacs.d/.cask/24.5.1/bootstrap/s-20160508.2357/s-autoloads.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/s-20160508.2357/s-autoloads.el
Checking /Users/james/.emacs.d/.cask/24.5.1/bootstrap/s-20160508.2357...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/s-20160508.2357/s-autoloads.el...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/s-20160508.2357/s-pkg.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/s-20160508.2357/s-pkg.elc
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/s-20160508.2357/s.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/s-20160508.2357/s.elc
Done (Total of 2 files compiled, 1 skipped)
Contacting host: melpa.org:443
Generating autoloads for dash.el...
Generating autoloads for dash.el...done
Saving file /Users/james/.emacs.d/.cask/24.5.1/bootstrap/dash-20160619.611/dash-autoloads.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/dash-20160619.611/dash-autoloads.el
Checking /Users/james/.emacs.d/.cask/24.5.1/bootstrap/dash-20160619.611...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/dash-20160619.611/dash-autoloads.el...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/dash-20160619.611/dash-pkg.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/dash-20160619.611/dash-pkg.elc
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/dash-20160619.611/dash.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/dash-20160619.611/dash.elc
Done (Total of 2 files compiled, 1 skipped)
Generating autoloads for f.el...
Generating autoloads for f.el...done
Saving file /Users/james/.emacs.d/.cask/24.5.1/bootstrap/f-20160426.527/f-autoloads.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/f-20160426.527/f-autoloads.el
Checking /Users/james/.emacs.d/.cask/24.5.1/bootstrap/f-20160426.527...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/f-20160426.527/f-autoloads.el...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/f-20160426.527/f-pkg.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/f-20160426.527/f-pkg.elc
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/f-20160426.527/f.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/f-20160426.527/f.elc
Done (Total of 2 files compiled, 1 skipped)
Generating autoloads for commander.el...
Generating autoloads for commander.el...done
Saving file /Users/james/.emacs.d/.cask/24.5.1/bootstrap/commander-20140120.1052/commander-autoloads.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/commander-20140120.1052/commander-autoloads.el
Checking /Users/james/.emacs.d/.cask/24.5.1/bootstrap/commander-20140120.1052...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/commander-20140120.1052/commander-autoloads.el...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/commander-20140120.1052/commander-pkg.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/commander-20140120.1052/commander-pkg.elc
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/commander-20140120.1052/commander.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/commander-20140120.1052/commander.elc
Done (Total of 2 files compiled, 1 skipped)
Contacting host: melpa.org:443
Generating autoloads for git.el...
Generating autoloads for git.el...done
Saving file /Users/james/.emacs.d/.cask/24.5.1/bootstrap/git-20140128.241/git-autoloads.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/git-20140128.241/git-autoloads.el
Checking /Users/james/.emacs.d/.cask/24.5.1/bootstrap/git-20140128.241...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/git-20140128.241/git-autoloads.el...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/git-20140128.241/git-pkg.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/git-20140128.241/git-pkg.elc
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/git-20140128.241/git.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/git-20140128.241/git.elc
Done (Total of 2 files compiled, 1 skipped)
Generating autoloads for epl.el...
Generating autoloads for epl.el...done
Saving file /Users/james/.emacs.d/.cask/24.5.1/bootstrap/epl-20150517.433/epl-autoloads.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/epl-20150517.433/epl-autoloads.el
Checking /Users/james/.emacs.d/.cask/24.5.1/bootstrap/epl-20150517.433...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/epl-20150517.433/epl-autoloads.el...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/epl-20150517.433/epl-pkg.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/epl-20150517.433/epl-pkg.elc
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/epl-20150517.433/epl.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/epl-20150517.433/epl.elc
Done (Total of 2 files compiled, 1 skipped)
Generating autoloads for shut-up.el...
Generating autoloads for shut-up.el...done
Saving file /Users/james/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522/shut-up-autoloads.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522/shut-up-autoloads.el
(No changes need to be saved)
Checking /Users/james/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522/shut-up-autoloads.el...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522/shut-up-pkg.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522/shut-up-pkg.elc
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522/shut-up.el...

In end of data:
shut-up.el:150:1:Warning: the following functions are not known to be defined:
    shut-up-write-region-original, shut-up-load-original
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522/shut-up.elc
Done (Total of 2 files compiled, 1 skipped)
Generating autoloads for package-build.el...
Generating autoloads for package-build.el...done
Saving file /Users/james/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160617.2029/package-build-autoloads.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160617.2029/package-build-autoloads.el
(No changes need to be saved)
Checking /Users/james/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160617.2029...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160617.2029/package-build-autoloads.el...
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160617.2029/package-build-pkg.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160617.2029/package-build-pkg.elc
Compiling /Users/james/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160617.2029/package-build.el...
Wrote /Users/james/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160617.2029/package-build.elc

Done (Total of 2 files compiled, 1 skipped)
Wrote /Users/james/.emacs.d/fork/xcode-mode/.cask/24.5.1/elpa/multiple-cursors-20160616.1404/multiple-cursors-autoloads.el
Wrote /Users/james/.emacs.d/fork/xcode-mode/.cask/24.5.1/elpa/dash-20160619.611/dash-autoloads.el
Wrote /Users/james/.emacs.d/fork/xcode-mode/.cask/24.5.1/elpa/s-20160508.2357/s-autoloads.el
Wrote /Users/james/.emacs.d/fork/xcode-mode/.cask/24.5.1/elpa/f-20160426.527/f-autoloads.el
Wrote /Users/james/.emacs.d/fork/xcode-mode/.cask/24.5.1/elpa/espuds-20151114.759/espuds-autoloads.el
Wrote /Users/james/.emacs.d/fork/xcode-mode/.cask/24.5.1/elpa/ansi-20150703.126/ansi-autoloads.el
Wrote /Users/james/.emacs.d/fork/xcode-mode/.cask/24.5.1/elpa/commander-20140120.1052/commander-autoloads.el
Wrote /Users/james/.emacs.d/fork/xcode-mode/.cask/24.5.1/elpa/ecukes-20150717.648/ecukes-autoloads.el

**Comment by nicklanasa** [comment]
I'm not experiencing this, although `travis-ci` is giving me a hard time and it resembles this.

I am seeing this though:

```
Warning: Lisp directory `/usr/local/Cellar/emacs/24.5/share/emacs/24.5/lisp/emacs-parallel': No such file or directory
Warning: Lisp directory `/usr/local/Cellar/emacs/24.5/share/emacs/24.5/lisp/emacs-parallel': No such file or directory
```

**Comment by jojojames** [comment]
I tried it on another computer and it looks like another error.

Scenario: Builds a project
    When I open a file "examples/test-project/.xctool-args"
    And I turn on xcode-mode
    And I press "C-M-x bb"
    And I switch to buffer "_compilation_"
    And I wait for compilation to finish
    Then I should see "BUILD SUCCEEDED"
      Expected
      BUILD SUCCEEDED
      to be part of:
      -_\- mode: compilation; default-directory: "~/.emacs.d/fork/xcode-mode/examples/test-project/" -_-
      Compilation started at Mon Jun 27 17:29:11

```
  xctool build
  [Info] Loading settings for scheme 'test-project' ...2016-06-27 17:29:14.331 xctool[15223:28403882] *** Assertion failure in -[XcodeSubjectInfo buildSettingsForATarget], /tmp/xctool20151025-93446-4sacdx/xctool-0.2.7/xctool/xctool/XcodeSubjectInfo.m:850

  2016-06-27 17:29:14.502 xctool[15223:28403882] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Failed while trying to gather build settings for your scheme; tried with actions: build, test, analyze. Errors above occured while running xcodebuild -showBuildSettings:
    2016-06-27 17:29:12.407 xcodebuild[15230:28403920] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  xcodebuild: error: Unable to find a destination matching the provided destination specifier:
        { name:iPhone 6 }

    The requested device could not be found because multiple devices matched the request.

    Available destinations for the "test-project" scheme:
        { platform:iOS Simulator, id:0F4F7178-531A-4F68-90B8-E22D089C4EAE, OS:9.2, name:iPad 2 }
        { platform:iOS Simulator, id:1C6C2606-21CF-4579-8478-613BEEB3BCC0, OS:9.3, name:iPad 2 }
        { platform:iOS Simulator, id:DBD58914-7C42-43AF-830E-161C05DD9687, OS:9.3, name:iPad 2 }
        { platform:iOS Simulator, id:915B4377-8889-462F-B8AC-FEBA8AC1DC33, OS:9.2, name:iPad Air }
        { platform:iOS Simulator, id:4AF3EB68-C1A6-4AF6-AF9F-B6D8430CD30E, OS:9.3, name:iPad Air }
        { platform:iOS Simulator, id:A85329BA-D0E2-494D-9221-6D25E629B0C2, OS:9.3, name:iPad Air }
        { platform:iOS Simulator, id:4DB64E34-B9E3-42A2-ACEE-9F2FDA6F0B08, OS:9.2, name:iPad Air 2 }
        { platform:iOS Simulator, id:143FC7B9-FA84-4069-8D6D-0F61F3F12E9B, OS:9.3, name:iPad Air 2 }
        { platform:iOS Simulator, id:BB3BC1AE-7459-46C3-B83D-4C274672F198, OS:9.3, name:iPad Air 2 }
        { platform:iOS Simulator, id:65F208C3-8FB5-4DDD-9492-BB6E6D518A71, OS:9.2, name:iPad Pro }
        { platform:iOS Simulator, id:3E38FBE8-D40E-4735-8076-68FF6EBF0DD6, OS:9.3, name:iPad Pro }
        { platform:iOS Simulator, id:E599D158-2CFC-4165-B8DC-643CAE4DEF40, OS:9.3, name:iPad Pro }
        { platform:iOS Simulator, id:1C4BF1A8-58DE-4FED-8B61-7D72B81E9CCC, OS:9.2, name:iPad Retina }
        { platform:iOS Simulator, id:89683078-FC46-4E5A-920A-D74F63A6CB36, OS:9.3, name:iPad Retina }
        { platform:iOS Simulator, id:8BAF8B04-1B4A-4669-93BF-651649C0162A, OS:9.3, name:iPad Retina }
        { platform:iOS Simulator, id:BEAC9E43-C684-4EA6-8603-82BE94F5AB6C, OS:9.2, name:iPhone 4s }
        { platform:iOS Simulator, id:975603B4-28F3-44B0-A83C-C923785D7DF9, OS:9.3, name:iPhone 4s }
        { platform:iOS Simulator, id:B9B38A2D-6F96-45FD-A39B-0526D6AAFA55, OS:9.3, name:iPhone 4s }
        { platform:iOS Simulator, id:8B06341E-B333-447A-A888-40ED8CBD6775, OS:9.2, name:iPhone 5 }
        { platform:iOS Simulator, id:AC9E4B95-0907-4CB3-8F02-593C9EEDF649, OS:9.3, name:iPhone 5 }
        { platform:iOS Simulator, id:C8D024F8-E5D3-4577-9A33-BAEB7DB133C7, OS:9.3, name:iPhone 5 }
        { platform:iOS Simulator, id:14197815-FE82-484C-BFD0-CA7295781FB2, OS:9.2, name:iPhone 5s }
        { platform:iOS Simulator, id:15FEF620-8678-49F8-B47A-3E9929DB779D, OS:9.3, name:iPhone 5s }
        { platform:iOS Simulator, id:1D805BB6-B3D2-42B6-8DA1-F575AAC1C0BF, OS:9.3, name:iPhone 5s }
        { platform:iOS Simulator, id:8DAD6D03-7A6A-4223-82A8-1DF6774F9885, OS:9.2, name:iPhone 6 }
        { platform:iOS Simulator, id:D0E226C8-B05A-4DD3-A5D9-A11F25BB843E, OS:9.3, name:iPhone 6 }
        { platform:iOS Simulator, id:DF115CEC-4FEE-4C3F-B734-B00EB21BF9B8, OS:9.3, name:iPhone 6 }
        { platform:iOS Simulator, id:30C98FAC-93F7-4F71-A85F-D824F1330A24, OS:9.2, name:iPhone 6 Plus }
        { platform:iOS Simulator, id:B2568DEC-2AA3-493C-AE4E-00E8A94CCC8F, OS:9.3, name:iPhone 6 Plus }
        { platform:iOS Simulator, id:BB50DF93-32C6-4C05-898F-52C0A0499EF8, OS:9.3, name:iPhone 6 Plus }
        { platform:iOS Simulator, id:80CC722F-96D4-4EB3-AA6A-0630D5F8E7EE, OS:9.2, name:iPhone 6s }
        { platform:iOS Simulator, id:BD47A991-D09A-4E5F-9187-1B7286904928, OS:9.3, name:iPhone 6s }
        { platform:iOS Simulator, id:D9968035-25C9-4110-8AF0-7DAA61ED6B87, OS:9.3, name:iPhone 6s }
        { platform:iOS Simulator, id:6639398A-7F8F-405C-996E-532D2E20802F, OS:9.2, name:iPhone 6s Plus }
        { platform:iOS Simulator, id:59299A2E-AD42-4F24-BAEC-B0945A37E2FE, OS:9.3, name:iPhone 6s Plus }
        { platform:iOS Simulator, id:C7EFBD5F-67E6-44E7-9D1A-F5AF12AA2057, OS:9.3, name:iPhone 6s Plus }
  .
    2016-06-27 17:29:13.110 xcodebuild[15234:28403956] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  xcodebuild: error: Unable to find a destination matching the provided destination specifier:
        { name:iPhone 6 }

    The requested device could not be found because multiple devices matched the request.

    Available destinations for the "test-project" scheme:
        { platform:iOS Simulator, id:0F4F7178-531A-4F68-90B8-E22D089C4EAE, OS:9.2, name:iPad 2 }
        { platform:iOS Simulator, id:1C6C2606-21CF-4579-8478-613BEEB3BCC0, OS:9.3, name:iPad 2 }
        { platform:iOS Simulator, id:DBD58914-7C42-43AF-830E-161C05DD9687, OS:9.3, name:iPad 2 }
        { platform:iOS Simulator, id:915B4377-8889-462F-B8AC-FEBA8AC1DC33, OS:9.2, name:iPad Air }
        { platform:iOS Simulator, id:4AF3EB68-C1A6-4AF6-AF9F-B6D8430CD30E, OS:9.3, name:iPad Air }
        { platform:iOS Simulator, id:A85329BA-D0E2-494D-9221-6D25E629B0C2, OS:9.3, name:iPad Air }
        { platform:iOS Simulator, id:4DB64E34-B9E3-42A2-ACEE-9F2FDA6F0B08, OS:9.2, name:iPad Air 2 }
        { platform:iOS Simulator, id:143FC7B9-FA84-4069-8D6D-0F61F3F12E9B, OS:9.3, name:iPad Air 2 }
        { platform:iOS Simulator, id:BB3BC1AE-7459-46C3-B83D-4C274672F198, OS:9.3, name:iPad Air 2 }
        { platform:iOS Simulator, id:65F208C3-8FB5-4DDD-9492-BB6E6D518A71, OS:9.2, name:iPad Pro }
        { platform:iOS Simulator, id:3E38FBE8-D40E-4735-8076-68FF6EBF0DD6, OS:9.3, name:iPad Pro }
        { platform:iOS Simulator, id:E599D158-2CFC-4165-B8DC-643CAE4DEF40, OS:9.3, name:iPad Pro }
        { platform:iOS Simulator, id:1C4BF1A8-58DE-4FED-8B61-7D72B81E9CCC, OS:9.2, name:iPad Retina }
        { platform:iOS Simulator, id:89683078-FC46-4E5A-920A-D74F63A6CB36, OS:9.3, name:iPad Retina }
        { platform:iOS Simulator, id:8BAF8B04-1B4A-4669-93BF-651649C0162A, OS:9.3, name:iPad Retina }
        { platform:iOS Simulator, id:BEAC9E43-C684-4EA6-8603-82BE94F5AB6C, OS:9.2, name:iPhone 4s }
        { platform:iOS Simulator, id:975603B4-28F3-44B0-A83C-C923785D7DF9, OS:9.3, name:iPhone 4s }
        { platform:iOS Simulator, id:B9B38A2D-6F96-45FD-A39B-0526D6AAFA55, OS:9.3, name:iPhone 4s }
        { platform:iOS Simulator, id:8B06341E-B333-447A-A888-40ED8CBD6775, OS:9.2, name:iPhone 5 }
        { platform:iOS Simulator, id:AC9E4B95-0907-4CB3-8F02-593C9EEDF649, OS:9.3, name:iPhone 5 }
        { platform:iOS Simulator, id:C8D024F8-E5D3-4577-9A33-BAEB7DB133C7, OS:9.3, name:iPhone 5 }
        { platform:iOS Simulator, id:14197815-FE82-484C-BFD0-CA7295781FB2, OS:9.2, name:iPhone 5s }
        { platform:iOS Simulator, id:15FEF620-8678-49F8-B47A-3E9929DB779D, OS:9.3, name:iPhone 5s }
        { platform:iOS Simulator, id:1D805BB6-B3D2-42B6-8DA1-F575AAC1C0BF, OS:9.3, name:iPhone 5s }
        { platform:iOS Simulator, id:8DAD6D03-7A6A-4223-82A8-1DF6774F9885, OS:9.2, name:iPhone 6 }
        { platform:iOS Simulator, id:D0E226C8-B05A-4DD3-A5D9-A11F25BB843E, OS:9.3, name:iPhone 6 }
        { platform:iOS Simulator, id:DF115CEC-4FEE-4C3F-B734-B00EB21BF9B8, OS:9.3, name:iPhone 6 }
        { platform:iOS Simulator, id:30C98FAC-93F7-4F71-A85F-D824F1330A24, OS:9.2, name:iPhone 6 Plus }
        { platform:iOS Simulator, id:B2568DEC-2AA3-493C-AE4E-00E8A94CCC8F, OS:9.3, name:iPhone 6 Plus }
        { platform:iOS Simulator, id:BB50DF93-32C6-4C05-898F-52C0A0499EF8, OS:9.3, name:iPhone 6 Plus }
        { platform:iOS Simulator, id:80CC722F-96D4-4EB3-AA6A-0630D5F8E7EE, OS:9.2, name:iPhone 6s }
        { platform:iOS Simulator, id:BD47A991-D09A-4E5F-9187-1B7286904928, OS:9.3, name:iPhone 6s }
        { platform:iOS Simulator, id:D9968035-25C9-4110-8AF0-7DAA61ED6B87, OS:9.3, name:iPhone 6s }
        { platform:iOS Simulator, id:6639398A-7F8F-405C-996E-532D2E20802F, OS:9.2, name:iPhone 6s Plus }
        { platform:iOS Simulator, id:59299A2E-AD42-4F24-BAEC-B0945A37E2FE, OS:9.3, name:iPhone 6s Plus }
        { platform:iOS Simulator, id:C7EFBD5F-67E6-44E7-9D1A-F5AF12AA2057, OS:9.3, name:iPhone 6s Plus }
```
